--AQUI VAMOS COMPARAR QUAIS CAMPOS EXISTEM ENTRE AS TABELAS
SELECT A.TABLE_NAME,
       A.COLUMN_NAME,
       A.DATA_TYPE,
       A.IS_NULLABLE,
       A.CHARACTER_MAXIMUM_LENGTH,
       --COLOCA OS CAMPOS DO BANCO SECUNDARIO
       B.TABLE_NAME,
       B.COLUMN_NAME,
       B.DATA_TYPE,
       B.IS_NULLABLE,
       B.CHARACTER_MAXIMUM_LENGTH
  FROM banco.INFORMATION_SCHEMA.COLUMNS AS A --SÓ ALTERA O NOME DO BANCO 
  FULL JOIN banco_producao.INFORMATION_SCHEMA.COLUMNS AS B --COLOCA O BANCO SECUNDARIO
    ON A.TABLE_NAME = B.TABLE_NAME COLLATE Latin1_General_CI_AS
   AND A.COLUMN_NAME = B.COLUMN_NAME COLLATE Latin1_General_CI_AS
