       --COLOCA OS CAMPOS DE DEV AQUI
SELECT A.TABLE_NAME,
       A.COLUMN_NAME,
       A.DATA_TYPE,
       A.IS_NULLABLE,
       A.CHARACTER_MAXIMUM_LENGTH,
       --COLOCA OS CAMPOS DA AMAZON AQUI
       B.TABLE_NAME,
       B.COLUMN_NAME,
       B.DATA_TYPE,
       B.IS_NULLABLE,
       B.CHARACTER_MAXIMUM_LENGTH
  FROM banco.INFORMATION_SCHEMA.COLUMNS AS A --SÓ ALTERA O NOME DO BANCO 
  FULL JOIN banco_producao.INFORMATION_SCHEMA.COLUMNS AS B --MANTENHA AMAZON_SAP. SÓ ALTERA O NOME O BANCO QUE ESTA EM HOMOLOG OU EM PROD
    ON A.TABLE_NAME = B.TABLE_NAME COLLATE Latin1_General_CI_AS
   AND A.COLUMN_NAME = B.COLUMN_NAME COLLATE Latin1_General_CI_AS
 --WHERE A.TABLE_NAME = 'TB_PF_CLIENTE' --CASO NECESSARIO PROCURE O NOME DA TABELA
 --WHERE B.COLUMN_NAME IS NULL --SÃO QUE EXISTE EM DEV QUE NÃO EXISTE EM PROD
 --WHERE A.COLUMN_NAME IS NULL --SÃO O QUE EXISTE EM PROD E NÃO EXITE EM DEV
