CREATE TABLE #TMP_ID_CAMPANHA
 (
	ID_CAMPANHA INT 
 )

 INSERT INTO #TMP_ID_CAMPANHA
 (
	ID_CAMPANHA 
 )
 VALUES(145), (146), (151), (152), (153), (154), (161), (162), (163), (164), (165), (166)

DECLARE @ID_CAMPANNHA_INICIO INT 
DECLARE @ID_CAMPANHA_FIM INT
DECLARE @NOME_TABELA VARCHAR(255)
DECLARE @SQL_DINAMICO VARCHAR(5000)

SET @ID_CAMPANNHA_INICIO  = (SELECT MIN(ID_CAMPANHA) FROM #TMP_ID_CAMPANHA)
SET @ID_CAMPANHA_FIM  = (SELECT MAX(ID_CAMPANHA) FROM #TMP_ID_CAMPANHA)

WHILE @ID_CAMPANNHA_INICIO <= @ID_CAMPANHA_FIM 
BEGIN

SET @NOME_TABELA = 'TMP_CAMP_' + CAST(@ID_CAMPANNHA_INICIO AS VARCHAR(255))

SET @SQL_DINAMICO = ' SELECT ID_CAMPANHA,
                             NOME_CAMPANHA,
                             TIPO_CAMPANHA,
                             DT_CAMPANHA,
                             CPF,
                             EMAIL,
                             CATEGORIA AS SEGMENTO 
                       INTO [NOME_BANCO].dbo.' + @NOME_TABELA + '
                       FROM TB_REGISTROS_CAMPANHA WITH (NOLOCK) 
                       WHERE ID_CAMPANHA = ' + CAST(@ID_CAMPANNHA_INICIO AS VARCHAR(255))
EXEC (@SQL_DINAMICO)

SET @ID_CAMPANNHA_INICIO = @ID_CAMPANNHA_INICIO + 1

END  
