---CRIAR CHAVE PRIMARIA

ALTER TABLE [TABELA]
ADD CONSTRAINT PK_NOME KEY ([TABELA])


--CRIAR CHAVE ESTRANGEIRA
ALTER TABLE [TABELA]
ADD CONSTRAINT FK_NOME
FOREIGN KEY (CAMPO) REFERENCES [TABELA](CAMPO);
