--CRIAÇÃO DA TABELA 
CREATE TABLE TMP_MONITORIA_REGUA
(
    DT_ENVIO                       VARCHAR(255)
   ,REGUA_CONSUMIVEIS              CHAR(1)
   ,REGUA_WELCOME_SISTEMA			     CHAR(1)
   ,WELCOME_HOMEPEDIA				       CHAR(1)
   ,NEWSLETTER_HOMPEDIA				     CHAR(1)
   ,REGUA_ANIVERSARIO_2_0_DIARIA	 CHAR(1)
   ,REGUA_CROSS_SELL				 CHAR(1)
   ,REGUA_UP_SELL					 CHAR(1)
   ,REGUA_GARANTIA_ESTENDIDA		 CHAR(1)
   ,REGUA_INATIVIDADE				 CHAR(1)
   ,INCENTIVO_DOWNLOAD_APP			 CHAR(1)
   ,REGUA_ANIVERSARIO_2_0_MENSAL	 CHAR(1)
   ,REGUA_OBRIGADO_PELA_COMPRA_ECOMM CHAR(1)
   ,REGUA_ONBOARDING_TOUCH_1		 CHAR(1)
   ,REGUA_ONBOARDING_TOUCH_2		 CHAR(1)
   ,REGUA_ONBOARDING__LAC12_LPR16	 CHAR(1)
)

--CRIAÇÃO DO PROCESSO
--CRIANDO UMA VARIAVEL DE DATA

DECLARE @DT_CAMPANHA VARCHAR(20)
DECLARE @QTD_REGISTROS INT

SET @DT_CAMPANHA =  '20200327'--CONVERT(VARCHAR, GETDATE(),112)

--VERIFICA SE A DATA EXISTE CASO EXISTIR NAO IREMOS INSERIR DE NOVO

IF NOT EXISTS(SELECT * FROM TMP_MONITORIA_REGUA WHERE DT_ENVIO = @DT_CAMPANHA)
BEGIN
      INSERT INTO TMP_MONITORIA_REGUA
      (
      	DT_ENVIO
      )
      VALUES(@DT_CAMPANHA)
END 

--FAZER AS VERIFICAÇÕES NA REGISTROS CAMPANHA
--7	REGUA_CONSUMIVEIS
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 7 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_CONSUMIVEIS = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_CONSUMIVEIS = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END 

--8	REGUA_WELCOME_SISTEMA
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 8 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_WELCOME_SISTEMA = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_WELCOME_SISTEMA = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END 

--9	WELCOME_HOMEPEDIA
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 9 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET WELCOME_HOMEPEDIA = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET WELCOME_HOMEPEDIA = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END 

--10	NEWSLETTER_HOMPEDIA
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 10 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET NEWSLETTER_HOMPEDIA = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET NEWSLETTER_HOMPEDIA = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END 

--11	REGUA_ANIVERSARIO_2.0_DIARIA
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 11 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_ANIVERSARIO_2_0_DIARIA = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_ANIVERSARIO_2_0_DIARIA = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END 

--11	REGUA_ANIVERSARIO_2.0_DIARIA
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 11 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_ANIVERSARIO_2_0_DIARIA = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_ANIVERSARIO_2_0_DIARIA = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--12	REGUA_CROSS_SELL
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 12 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_CROSS_SELL = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_CROSS_SELL = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--15	REGUA_UP_SELL
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 15 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_UP_SELL = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_UP_SELL = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--16	REGUA_GARANTIA_ESTENDIDA
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 16 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_GARANTIA_ESTENDIDA = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_GARANTIA_ESTENDIDA = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--17	REGUA_INATIVIDADE
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 17 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_INATIVIDADE = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_INATIVIDADE = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--19	INCENTIVO_DOWNLOAD_APP
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 19 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET INCENTIVO_DOWNLOAD_APP = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET INCENTIVO_DOWNLOAD_APP = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--21	REGUA_ANIVERSARIO_2.0_MENSAL
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 21 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_ANIVERSARIO_2_0_MENSAL = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_ANIVERSARIO_2_0_MENSAL = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END


--25	REGUA_OBRIGADO_PELA_COMPRA_ECOMM
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 25 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_OBRIGADO_PELA_COMPRA_ECOMM = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_OBRIGADO_PELA_COMPRA_ECOMM = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--32	REGUA_ONBOARDING_TOUCH_1
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 32 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_ONBOARDING_TOUCH_1 = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_ONBOARDING_TOUCH_1 = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--35	REGUA_ONBOARDING_TOUCH_2
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 35 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_ONBOARDING_TOUCH_2 = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_ONBOARDING_TOUCH_2 = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

--36	REGUA_ONBOARDING__LAC12_LPR16
SET @QTD_REGISTROS = (SELECT COUNT(*) FROM [CLIENTE].dbo.TB_REGISTROS_CAMPANHA WHERE ID_CAMPANHA = 36 AND CAST(DT_CAMPANHA AS date) = CAST(@DT_CAMPANHA AS DATE))

IF @QTD_REGISTROS > 0 
  BEGIN
  	    UPDATE TMP_MONITORIA_REGUA
  	       SET REGUA_ONBOARDING__LAC12_LPR16 = 'O'
  	     WHERE DT_ENVIO = @DT_CAMPANHA 
  END 
ELSE 
    BEGIN 
		UPDATE TMP_MONITORIA_REGUA
	       SET REGUA_ONBOARDING__LAC12_LPR16 = 'X'
	     WHERE DT_ENVIO = @DT_CAMPANHA 
    END

SELECT * 
  FROM TMP_MONITORIA_REGUA
