/*
CRUZAMENTOS DE TABELA
*/
--INNER JOIN(QUANDO AS INFORMAÇÕES DE AMBAS AS TABELAS TEM QUE SER IGUAIS
SELECT [CAMPOS] ......  --AQUI VC VAI TRAZER OS CAMPOS NECESSARIOS 
  FROM [TABELA_A] AS A
 INNER JOIN [TABELA_B] 
  ON A.CAMPO_A = A.CAMPO_B

--LEFT JOIN (SIGNIFICA QUE VAMOS PRIORIZAR A TABELA DA ESQUERDA, EM OUTRAS PALAVRAS VAMOS TRAZER TUDO DA TABELA DA ESQUERDA E O QUE EXISTIR NA TABELA DA DIREITA)
SELECT [CAMPOS] ......  --AQUI VC VAI TRAZER OS CAMPOS NECESSARIOS 
  FROM [TABELA_A] AS A
  LEFT JOIN [TABELA_B] 
  ON A.CAMPO_A = A.CAMPO_B

  --RIGHT JOIN (SIGNIFICA QUE VAMOS PRIORIZAR A TABELA DA DIREITA, EM OUTRAS PALAVRAS VAMOS TRAZER TUDO DA TABELA DA DIREITA E O QUE EXISTIR NA TABELA DA ESQUERDA)
SELECT [CAMPOS] ......  --AQUI VC VAI TRAZER OS CAMPOS NECESSARIOS 
  FROM [TABELA_A] AS A
  RIGHT JOIN [TABELA_B] 
  ON A.CAMPO_A = A.CAMPO_B
  
  --FULL JOIN (E A JUNCAO DO INNER E LEFT E RIGHT MAIS O QUE EXISTE NA TABELA DA ESQUERADA QUE NAO EXISTE NA DIREITA E VICE VERSA)
  SELECT [CAMPOS] ......  --AQUI VC VAI TRAZER OS CAMPOS NECESSARIOS 
  FROM [TABELA_A] AS A
  FULL JOIN [TABELA_B] 
  ON A.CAMPO_A = A.CAMPO_B

  /*
	APLICANDO ESSES CONCEITOS PODEMOS CRIAR SUBQUERIES DENTRO DE CRIZAMENTOS TAMBEM
  */
  --AQUI SEGUE O EXEMPLO COM INNER. 
 SELECT [CAMPOS] ......  --AQUI VC VAI TRAZER OS CAMPOS NECESSARIOS 
  FROM [TABELA_A] AS A
 INNER JOIN (SELECT CAMPO_A,CAMPO_B,CAMPO_C FROM [TABELA_B]) AS B 
  ON A.CAMPO_A = A.CAMPO_B
 
 