CREATE PROCEDURE SP_TRATAMENTO_PADRAO

@BANCO_DE_DADOS VARCHAR(500), 
@NOME_TABELA VARCHAR(500),
@DATATYPE VARCHAR(500)

AS

--VARIAVEIS QUE VÃO FAZER PERCORRER O CAMPO ID
DECLARE @ID_INICIO INT
DECLARE @ID_FIM INT

--VARIAVEIS DE CRIAÇÃO DA TABELA
DECLARE @SQL_INFORMATION_SCHEMA VARCHAR(2000)

--VARIAVEL QUE VAI RECEBER O COMANDO SQL
DECLARE @SQL VARCHAR(2000)

SET @SQL_INFORMATION_SCHEMA = '  USE '+ @BANCO_DE_DADOS +'
                                 IF OBJECT_ID(''TEMPDB..##TMP_INFORMATION_SCHEMA'') <> 0
								 DROP TABLE ##TMP_INFORMATION_SCHEMA

                                  SELECT *
							        INTO ##TMP_INFORMATION_SCHEMA
							        FROM '+@BANCO_DE_DADOS+'.INFORMATION_SCHEMA.COLUMNS  
							       WHERE TABLE_NAME = '''+ @NOME_TABELA +'''
							         AND DATA_TYPE = '''+@DATATYPE+''''

EXEC (@SQL_INFORMATION_SCHEMA)


--VARIAVEL DE TABELA
DECLARE @TABELA AS TABLE (ID INT IDENTITY
                         ,COMANDO_SQL VARCHAR(2000))

INSERT INTO @TABELA
(
	COMANDO_SQL
)
SELECT 'UPDATE '+ TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME + ' SET ['+ COLUMN_NAME +'] = NULLIF(LTRIM(RTRIM(['+ COLUMN_NAME +'])),'''')' AS COMANDO_SQL
  FROM ##TMP_INFORMATION_SCHEMA

SET @ID_INICIO = (SELECT MIN(ID) FROM @TABELA) --1
SET @ID_FIM = (SELECT MAX(ID) FROM @TABELA) --30

--LOOP PERCORRENDO O CAMPO ID
WHILE @ID_INICIO <= @ID_FIM
BEGIN
	SET @SQL = (SELECT COMANDO_SQL FROM @TABELA WHERE ID = @ID_INICIO)
	EXEC(@SQL)

	SET @ID_INICIO = @ID_INICIO + 1
END 
